### ISSUE TITLE
Add support for GPT2ForSequenceClassification classification 

### ISSUE THREAD

**Issue by cdpierse** [cdpierse/transformers-interpret#13]
When testing `SequenceClassificationExplainer` out with [DialogRPT](https://huggingface.co/microsoft/DialogRPT-updown) which uses the GPT2 sequence classification head I noticed that it fails. 

So far I can see two reasons for this:
- the BOS and EOS tokens are handled differently. 
- The embeddings cannot be fetched the same way as they are with BERT like models

**Comment by kanishkamisra** [comment]
Hi! Has this been implemented?
