### ISSUE TITLE
base_model_prefix

### ISSUE THREAD

**Issue by vivicenisilva** [cdpierse/transformers-interpret#28]
I love this library ❤️  However, I am trying to use it with a fine-tuned BERT classifier, but I keep getting:

_`"AttributeError: 'ClassificationModel' object has no attribute 'base_model_prefix".`_ 

My first question, does the interpreter work if I load a community fine-tuned model? According to the doc, it should work with all classification transformer models. So, I don't quite get the issue here.

Second, I tried to hard-code it in the code (explainer.py), but I keep getting the same error.

`self.model_prefix = "bert"` 

Any ideas?

Thanks!

**Comment by cdpierse** [comment]
Hi @vivicenisilva, thanks so much for trying out the package, I'm really glad you're enjoying it. 

Regarding the issue you are having are you using a community model with a sequence classification head from the Huggingface library itself ? If so can I ask what model it is so I can test it out for myself ?

The package currently supports classification models that use the classification head added by the Huggingface team. So if you were for example to instantiate your own pytorch model where one of the layers is a Base bert model and another layer is a linear layer it wouldn't work.

The model must be of the huggingface model class `{ModelName}ForSequenceClassification`. 

The example below shows how models must be instantiated, note that I am using `AutoModelForSequenceClassification` to specify the model. 

```python 
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from transformers_interpret import SequenceClassificationExplainer
from transformers_interpret.errors import (
    AttributionTypeNotSupportedError,
    InputIdsNotCalculatedError,
)

DISTILBERT_MODEL = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased-finetuned-sst-2-english"
)
DISTILBERT_TOKENIZER = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased-finetuned-sst-2-english"
)

seq_explainer = SequenceClassificationExplainer(
        DISTILBERT_MODEL, DISTILBERT_TOKENIZER
)

```

**Comment by vivicenisilva** [comment]
Hi @cdpierse thank you for your swift reply, and sorry for not getting back to you sooner! 😅

So, I am using a wrapper called simpletransformers (https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/classification_model.py). The classification model is _BertForSequenceClassification_.

Then I fine-tuned the Dutch pre-trained model (https://github.com/wietsedv/bertje) with my dataset.

Does this information help?

Thanks!
Virginia

**Comment by cdpierse** [comment]
Hi @vivicenisilva ,

No problem at all, we get back when we can :-). So I've not used the simpletransformers package before but I just took a quick look at the source code, and I think the solution below _might_ solve your issue. Since simple transformers is essentially just a wrapper you should be able to access the model and tokenizer as class attributes. 

```python 

from transformers_interpret import SequenceClassificationExplainer

... # intialize your simpletransformers model as `classification_model`

# model and tokenizer are just attributes of the simpletransformers model
seq_explainer = SequenceClassificationExplainer(
        classification_model.model, 
        classification_model.tokenizer 
)
...
```

Give this a go and let me know if it works, I think it should.

**Comment by vivicenisilva** [comment]
You're right @cdpierse. It works now! 

Thanks,
Virginia

**Comment by cdpierse** [comment]
@vivicenisilva That's great. Glad it worked. Thanks for raising this, it's good to know it works okay with that package now.
