### ISSUE TITLE
Adding contribution guideline

### ISSUE THREAD

**Issue by lalitpagaria** [cdpierse/transformers-interpret#42]
@cdpierse 
While contributing one PR to this awesome repo, I observed that it would be great to have contribution guideline.

Some of possible points can be added to this guide are -
- Fork the repo [If not done]
- Fetch upstream (`git fetch upstream`)
- Checkout `dev` branch
- Rebase `dev` branch with upstream (`git rebase upstream/dev`)
- Create new branch and add changes to that branch
- Add/update/remove relevant test cases
- Perform `black` formatting on changes
- Raise PR against upstream dev branch
- Ask for the review

Few observations about CI process -
- CI should run on every PR, so PR raiser will get feedback about test failure or build issue early
- Currently PR merge is very open, it does not check for PR approval and CI pass status

**Comment by cdpierse** [comment]
@lalitpagaria this is definitely a top priority, will hopefully be able to dedicate the weekend to getting a decent and thorough guide out.
