### ISSUE TITLE
What can be done for MultipleChoice Models ? 

### ISSUE THREAD

**Issue by prajjwal1** [cdpierse/transformers-interpret#43]
I want to get some info about sentence importance. So my models are `ForMultipleChoice` from HF `transformers`. I was wondering if you've any suggestions on getting importance scores. I am mostly interested in finding out which tokens are primarily responsible for giving out a correct option. I also talked about it [here](https://discuss.huggingface.co/t/approach-to-get-info-about-word-importance/6304). You seem to have done something similar with regards to sentence classification. If you've any suggestions for Multiple choice use case, I am happy to try out `transformers-interpret`, I do know its on the roadmap. If not, feel free to close this issue.

**Comment by nicksome168** [comment]
Is there any updates on this issue? I'm looking for the same thing here too.

**Comment by cdpierse** [comment]
Hi @prajjwal1 @nicksome168 as of right now I haven't started working on an implementation for this explainer as I'm currently working on  an NER explainer for the next release and at the moment I tend to do one at a time. Once I have the NER explainer done I should be able to switch my focus to getting a prototype for this done.
