### ISSUE TITLE
CUDA out of memory when using Longformer base model

### ISSUE THREAD

**Issue by szamani20** [cdpierse/transformers-interpret#51]
Thank you for your amazing work.
I want to use your transformer interpreter to explain a `Longformer` model. I literally replace `distilbert-base-uncased-finetuned-sst-2-english` with `allenai/longformer-base-4096` and I encounter a CUDA out of memory error. I don't touch anything else at all. Just changed the model name in the example provided in the README file.

I'm using Google Colab and it has no issue with training Longformer model. Is this a known issue?
16000 MB of GPU memory should be enough for such task. Is there any workaround to quickly fix this? Thank you.

Package Version:
0.5.0

GPU spec:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    28W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-8b25e2022be5> in <module>()
----> 1 word_attributions = cls_explainer("I love you, I like you")
      2 word_attributions

22 frames
/usr/local/lib/python3.7/dist-packages/transformers/models/longformer/modeling_longformer.py in forward(self, hidden_states, attention_mask, layer_head_mask, is_index_masked, is_index_global_attn, is_global_attn, output_attentions)
    650 
    651         # softmax sometimes inserts NaN if all positions are masked, replace them with 0
--> 652         attn_probs = torch.masked_fill(attn_probs, is_index_masked[:, :, None, None], 0.0)
    653         attn_probs = attn_probs.type_as(attn_scores)
    654 

RuntimeError: CUDA out of memory. Tried to allocate 604.00 MiB (GPU 0; 15.90 GiB total capacity; 14.28 GiB already allocated; 357.75 MiB free; 14.67 GiB reserved in total by PyTorch)
```

**Comment by cdpierse** [comment]
Hi @szamani20 thanks a lot for using the package. The problem you are encountering isn't too surprising actually as it lies mostly with how the interpretations are calculated and the large input size for Longformer, I also noticed that the model you provided `allenai/longformer-base-4096` is just a base LM it doesn't have a sequence classification head like it should if you are trying to explain classifications. Even without the OOM issue this model won't work for sequence classification as is. 

Back to the OOM issue what I think is going on is that the way integrated gradients are calculated is by integrating a baseline (padded) input's prediction into the actual input's prediction and this occurs over a number of steps, be default I believe these steps are set to 50. At each step over this integration the gradients are accumulated, with a large model like longformer and with the already limited memory of GPU's I would guess this is what causes the OOM. The best solutions for this would be a larger GPU or to not use a GPU for generating explanations and instead use CPU.

**Comment by szamani20** [comment]
Thank you for responding so quickly! I actually have trained the model on a binary classification task, but for the simplicity didn't include that part of the code here. So the model I'm feeding the interpreter is actually a specific checkpoint of a trained binary classifier.
I didn't know much about the details you provided, but I assume if the current GPU is fine with fine tuning the model, then there shouldn't be any issue with interpreting it. Am I missing something?

More complete code:

GPU usage here: **0**

```
tokenizer = AutoTokenizer.from_pretrained('allenai/longformer-base-4096', model_max_length=1500)
model = AutoModelForSequenceClassification.from_pretrained('./train/checkpoint-1300')  # checkpoint-1300 contains the saved model fine tuned on a binary classification task
cls_explainer = SequenceClassificationExplainer(model, tokenizer)
```

Up until here the GPU usage is only **1519MiB / 16280MiB**

Then:

```
word_attributions = cls_explainer('A very short 100 character text here!')
```

Error (included in the original post, but again here):

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-8b25e2022be5> in <module>()
----> 1 word_attributions = cls_explainer(music_test_df['text'].tolist()[0][:100])
      2 word_attributions

22 frames
/usr/local/lib/python3.7/dist-packages/transformers/models/longformer/modeling_longformer.py in forward(self, hidden_states, attention_mask, layer_head_mask, is_index_masked, is_index_global_attn, is_global_attn, output_attentions)
    650 
    651         # softmax sometimes inserts NaN if all positions are masked, replace them with 0
--> 652         attn_probs = torch.masked_fill(attn_probs, is_index_masked[:, :, None, None], 0.0)
    653         attn_probs = attn_probs.type_as(attn_scores)
    654 

RuntimeError: CUDA out of memory. Tried to allocate 604.00 MiB (GPU 0; 15.90 GiB total capacity; 14.28 GiB already allocated; 357.75 MiB free; 14.67 GiB reserved in total by PyTorch)
```

**Comment by cdpierse** [comment]
Hi @szamani20, I think the best analogue here would be to compare how attributions are calculated with batch sizes when training. 

Since you've trained your own model you've probably noticed that batch size is a finicky hyperparamater and given that your GPU has 16GB of RAM you probably have had to set the batch size relatively low (<16). 

The way Captum works is very similar in that it accumulates gradients about 50 times in order to derive its explanation, this load on the GPU is effectively the same as storing the gradients of a batch of 50 on the GPU device, which would be too much. It might be a nice idea for me to add `n_steps` as a controllable parameter but I'm a little hesitant as the default is 50 and I'd worry that explanations will become less meaningful the lower it goes.

**Comment by szamani20** [comment]
Thank you for your quick response! Is there any way to explicitly tell the `SequenceClassificationExplainer` to only use CPU? I'm asking because it seems that if a GPU is available it will use it anyway (and if I make it unavailable, Colab will reset everything and I lose training info)

Also, I couldn't find anywhere in the source code where I can change the batch size from default 50. Longformer occupies so much memory that for a tokenizer with `max_length` of 1500 tokens, you can have a maximum of 2 for batch size. So I assume 50 is way more than what a 16GB GPU could hold.

**Comment by cdpierse** [comment]
It sounds like Longformer combined with 50 steps in the explainer might be pushing things a bit too much in terms of gradient accumulation. I'll have to put together a PR to possibly add a custom n_steps for the attributions, I'll definitely added it although I am a little hesitant to do so as it might lead to some less than accurate model interpretations. It's still worth adding though so hopefully I can get onto this in the next week or so.

**Comment by cdpierse** [comment]
@szamani20 this latest version should now be able to handle Longformers gradients. If you update your version to `0.5.1` the only change you need to make is to the explainer instance:
From 
```python
cls_explainer('A very short 100 character text here!')
```
To 
```python
cls_explainer('A very short 100 character text here!',internal_batch_size=1)
```

I'm pretty confident this fix should be able to prevent the explainer from going OOM in both CPU and GPU instances.
