### ISSUE TITLE
Explainers for two input classification problem

### ISSUE THREAD

**Issue by isspek** [cdpierse/transformers-interpret#58]
Thanks for the project. 

My question is that if we have an input composed of two sentences for a classification problem, which should be separated with a [SEP] token, how can we set up the explainers? As I understand from the source code, it encodes single text.

**Comment by cdpierse** [comment]
Hi @isspek 

Thanks for using the package! So this is certainly doable as I do it for the QA explainer but I just hadn't thought to add the functionality for the classification explainer. I think it would only be a matter of adding an additional optional param to the explainer call method but I'll have to have a think on how to do it. 

I should have some time to have a look at it over the weekend and see what's involved.

**Comment by savasy** [comment]
Good question! I wonder how to do  :)
