### ISSUE TITLE
Can I use this for Sentence similarity models ? 

### ISSUE THREAD

**Issue by Threepointone4** [cdpierse/transformers-interpret#63]
How can i use this for sentence similarity models ? Lets say i have 2 texts and have a cosine similarity value, Can I see what words contributed and other details ? Thanks in advance.

**Comment by cdpierse** [comment]
Hi @Threepointone4 this is something I'd love to figure out but I don't know how feasible it is to do right now. The problem with what you have described above is that the model output's a sentence embedding for each sentence for each input sentence and after the cosine similarity is applied so any similarity being calculated would relate to the positional embeddings and not the words themselves. From what I know it is difficult to relate a specific position in an embedding to a single concept or word. Even creating explanations from the sentence to the embedding is hard as there are usually 768 different positions to provide explanations for.
