### ISSUE TITLE
Link to paper?

### ISSUE THREAD

**Issue by mosh98** [cdpierse/transformers-interpret#67]
Hi, could you please link me the paper that this repo is adapted to?

**Comment by cdpierse** [comment]
Hi @mosh98  the repo isn't directly adapting any part paper. The code wraps around the Pytorch Captum package which itself contains an implementation of Integrated Gradients as laid out in the paper Axiomatic Attributions for Deep Networks

**Comment by mosh98** [comment]
Ok i see, i'll look into it.

Good contribution btw!

Have a nice day
