### ISSUE TITLE
Pass Tokens Instead of String 

### ISSUE THREAD

**Issue by JosephGatto** [cdpierse/transformers-interpret#85]
Is it possible to, instead of passing in a string and tokenizer, pass in the individual parameters required by model.forward? 

E.g., instead of passing a string, I can provide input_ids, attention_mask, etc. 

I have a custom BERT model with different/additional parameters I'd like to inspect.

**Comment by cdpierse** [comment]
Hi @JosephGatto,

This is an interesting use case and not one that I considered. I think that the changes required across all of the package's internals to accommodate custom input types outside of the standard model inputs would effectively negate the value of the package. If I were you I'd recommend either: 
- subclassing the BaseExplainer yourself and using some of the wrappers the package provides
- use the [Captum ](https://captum.ai/) package directly using some of the [examples](https://captum.ai/tutorials/Bert_SQUAD_Interpret) as a launching point. 

Hope this helps somewhat.

**Comment by JosephGatto** [comment]
Thanks!!
