### ISSUE TITLE
Tips for using Pairwise Inputs? 

### ISSUE THREAD

**Issue by JosephGatto** [cdpierse/transformers-interpret#87]
I tried just passing 'input 1 [SEP] input 2' but kept getting the wrong predicted label from the SingleLabelClassifier -- I assume its because the tokenizer isn't assigning token_type_ids. Is there any hacky-way to fix this?

**Comment by cdpierse** [comment]
Hey this has been closed by #99 please use the `PairwiseSequenceClassificationExplainer` as this now assigns the correct token_type_ids for pairwise problems 😄
