### ISSUE TITLE
can batch and token_ids input ?

### ISSUE THREAD

**Issue by WenxiongLiao** [cdpierse/transformers-interpret#94]
As seen from [transformers-interpret](https://github.com/cdpierse/transformers-interpret)/[notebooks](https://github.com/cdpierse/transformers-interpret/tree/master/notebooks)/multiclass_classification_example.ipynb, the input to [transformers-interpret](https://github.com/cdpierse/transformers-interpret) is the text of a single sentence

**can we input a batch? or  input  token_ids?**

**Comment by cdpierse** [comment]
Hi @WenxiongLiao  batching is on our roadmap for sometime in the future but we have a few more release we'd like to get done first. Thanks!
